# Generated by Django 4.0.2 on 2022-02-07 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ishchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasmi', models.ImageField(upload_to='')),
                ('ismi', models.CharField(max_length=300)),
                ('familiyasi', models.CharField(max_length=300)),
                ('nima_qigan', models.TextField()),
                ('qayerda_oqigan', models.CharField(blank=True, max_length=300)),
                ('ish_darajasi', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Loyiha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=400)),
                ('rasmi', models.ImageField(upload_to='')),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyiha.kategoriya')),
            ],
        ),
    ]
