# Generated by Django 2.2.16 on 2022-02-10 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyiha',
            name='ishchi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loyihalar', to='loyiha.Ishchi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ishchi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kategoriya',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loyiha',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
